# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-28 12:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmailData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('subject', models.CharField(max_length=10000)),
                ('mail_id', models.IntegerField(default=0, unique=True)),
                ('cc', models.ManyToManyField(related_name='cc', to='email_data.Email')),
                ('from_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_email', to='email_data.Email')),
            ],
            options={
                'ordering': ('-mail_id',),
            },
        ),
        migrations.CreateModel(
            name='MailingList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_id', models.EmailField(max_length=254, unique=True)),
                ('contact', models.EmailField(max_length=254)),
                ('totalPosts', models.IntegerField()),
                ('unanswered', models.IntegerField()),
                ('lastAdminPostDate', models.DateTimeField(blank=True)),
                ('lastUserPostDate', models.DateTimeField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='emaildata',
            name='mailing_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='email_data.MailingList'),
        ),
        migrations.AddField(
            model_name='emaildata',
            name='to_email',
            field=models.ManyToManyField(related_name='to_email', to='email_data.Email'),
        ),
    ]
