# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-09 20:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmailBody',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(default='', max_length=1000)),
                ('in_reply_id', models.CharField(max_length=1000, null=True)),
                ('contentType', models.CharField(max_length=20)),
                ('body', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='EmailData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('to_email', models.TextField()),
                ('cc', models.TextField()),
                ('subject', models.CharField(max_length=10000)),
                ('mail_id', models.IntegerField(default=0, unique=True)),
                ('from_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_email', to='email_data.Email')),
            ],
            options={
                'ordering': ('-mail_id',),
            },
        ),
        migrations.CreateModel(
            name='MailingList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_id', models.EmailField(max_length=254, unique=True)),
                ('contact', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Threads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_ids', models.TextField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='emaildata',
            name='mailing_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='email_data.MailingList'),
        ),
        migrations.AddField(
            model_name='emaildata',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='email_data.Threads'),
        ),
        migrations.AddField(
            model_name='emailbody',
            name='email_data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='email_data.EmailData'),
        ),
    ]
