# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-09 21:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('email_data', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailbody',
            old_name='in_reply_id',
            new_name='in_reply_to',
        ),
    ]
