# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-28 12:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailinglist',
            name='lastAdminPostDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='mailinglist',
            name='lastUserPostDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='mailinglist',
            name='totalPosts',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mailinglist',
            name='unanswered',
            field=models.IntegerField(default=0),
        ),
    ]
