# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-29 15:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('email_data', '0002_auto_20171228_1232'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailBody',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contentType', models.CharField(max_length=20)),
                ('body', models.TextField()),
                ('email_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='email_data.EmailData')),
            ],
        ),
    ]
