# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-05 00:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('email_data', '0003_emailbody'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailinglist',
            name='lastAdminPostDate',
        ),
        migrations.RemoveField(
            model_name='mailinglist',
            name='lastUserPostDate',
        ),
        migrations.RemoveField(
            model_name='mailinglist',
            name='totalPosts',
        ),
        migrations.RemoveField(
            model_name='mailinglist',
            name='unanswered',
        ),
    ]
