# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-05 23:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_data', '0004_auto_20180105_0033'),
    ]

    operations = [
        migrations.CreateModel(
            name='FullEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail_id', models.IntegerField(default=0)),
                ('data', models.TextField()),
            ],
        ),
    ]
