# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-07 17:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_data', '0005_fullemail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FullEmail',
        ),
        migrations.AddField(
            model_name='emaildata',
            name='in_reply_id',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='emaildata',
            name='message_id',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
